[package]
name = "polya"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "lean-3.4.2"} 
smt2_interface = {git = "https://github.com/leanprover/smt2_interface", rev = "8225227641ac3033bc82e939dc66edb1ae4fb720"}
